model_verbosity = "low"
web_search = "live"
sandbox_mode = "danger-full-access"

[mcp_servers.ai-game-developer]
enabled = true
startup_timeout_sec = 30
tool_timeout_sec = 300
url = "https://ai-game.dev/mcp/p/edd989cc"

[mcp_servers.ai-game-developer.tools.assets-refresh]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.script-execute]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.tests-run]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-create]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-add]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-modify]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.scene-save]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-destroy]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-modify]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-create]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-destroy]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-open]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-close]
approval_mode = "approve"
